#############################################################################
# Makefile for building: iot
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  iot.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile iot.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Ilib/mqtt-inc -Ilib/QtTelegramBot -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = iot1.0.0
DISTDIR = /opt/iot/.tmp/iot1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lwiringPi -lQt5Qmqtt -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGLESv2 -lpthread -latomic 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = lib/QtTelegramBot/qttelegrambot.cpp \
		lib/QtTelegramBot/networking.cpp \
		lib/QtTelegramBot/types/message.cpp \
		lib/QtTelegramBot/types/update.cpp \
		lib/QtTelegramBot/types/chat.cpp \
		lib/QtTelegramBot/types/user.cpp \
		lib/QtTelegramBot/types/document.cpp \
		lib/QtTelegramBot/types/photosize.cpp \
		lib/QtTelegramBot/types/audio.cpp \
		lib/QtTelegramBot/types/sticker.cpp \
		lib/QtTelegramBot/types/video.cpp \
		lib/QtTelegramBot/types/voice.cpp \
		lib/QtTelegramBot/types/contact.cpp \
		lib/QtTelegramBot/types/location.cpp \
		main.cpp \
		widget.cpp \
		process.cpp \
		settings.cpp \
		dht.cpp \
		qcustomplot.cpp moc_qttelegrambot.cpp \
		moc_networking.cpp \
		moc_widget.cpp \
		moc_process.cpp \
		moc_dht.cpp \
		moc_qcustomplot.cpp
OBJECTS       = qttelegrambot.o \
		networking.o \
		message.o \
		update.o \
		chat.o \
		user.o \
		document.o \
		photosize.o \
		audio.o \
		sticker.o \
		video.o \
		voice.o \
		contact.o \
		location.o \
		main.o \
		widget.o \
		process.o \
		settings.o \
		dht.o \
		qcustomplot.o \
		moc_qttelegrambot.o \
		moc_networking.o \
		moc_widget.o \
		moc_process.o \
		moc_dht.o \
		moc_qcustomplot.o
DIST          = /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		lib/QtTelegramBot/QtTelegramBot.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		iot.pro lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		widget.h \
		settings.h \
		process.h \
		settings.h \
		dht.h \
		defines.h \
		qcustomplot.h lib/QtTelegramBot/qttelegrambot.cpp \
		lib/QtTelegramBot/networking.cpp \
		lib/QtTelegramBot/types/message.cpp \
		lib/QtTelegramBot/types/update.cpp \
		lib/QtTelegramBot/types/chat.cpp \
		lib/QtTelegramBot/types/user.cpp \
		lib/QtTelegramBot/types/document.cpp \
		lib/QtTelegramBot/types/photosize.cpp \
		lib/QtTelegramBot/types/audio.cpp \
		lib/QtTelegramBot/types/sticker.cpp \
		lib/QtTelegramBot/types/video.cpp \
		lib/QtTelegramBot/types/voice.cpp \
		lib/QtTelegramBot/types/contact.cpp \
		lib/QtTelegramBot/types/location.cpp \
		main.cpp \
		widget.cpp \
		process.cpp \
		settings.cpp \
		dht.cpp \
		qcustomplot.cpp
QMAKE_TARGET  = iot
DESTDIR       = 
TARGET        = iot


first: all
####### Build rules

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iot.pro /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf \
		lib/QtTelegramBot/QtTelegramBot.pri \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf \
		/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf \
		iot.pro \
		/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Network.prl \
		/usr/lib/arm-linux-gnueabihf/libQt5Core.prl
	$(QMAKE) -o Makefile iot.pro
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/linux.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/sanitize.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-base.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/qconfig.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/toolchain.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_pre.prf:
lib/QtTelegramBot/QtTelegramBot.pri:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/default_post.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/warn_on.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qt.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/resources.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/moc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/uic.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/file_copies.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/exceptions.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/yacc.prf:
/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/lex.prf:
iot.pro:
/usr/lib/arm-linux-gnueabihf/libQt5PrintSupport.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Widgets.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Gui.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Network.prl:
/usr/lib/arm-linux-gnueabihf/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile iot.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents lib/QtTelegramBot/qttelegrambot.h lib/QtTelegramBot/networking.h lib/QtTelegramBot/types/message.h lib/QtTelegramBot/types/update.h lib/QtTelegramBot/types/chat.h lib/QtTelegramBot/types/user.h lib/QtTelegramBot/types/file.h lib/QtTelegramBot/types/document.h lib/QtTelegramBot/types/photosize.h lib/QtTelegramBot/types/audio.h lib/QtTelegramBot/types/sticker.h lib/QtTelegramBot/types/video.h lib/QtTelegramBot/types/voice.h lib/QtTelegramBot/types/contact.h lib/QtTelegramBot/types/location.h lib/QtTelegramBot/types/reply/genericreply.h lib/QtTelegramBot/types/reply/replykeyboardmarkup.h lib/QtTelegramBot/types/reply/replykeyboardhide.h lib/QtTelegramBot/types/reply/forcereply.h widget.h settings.h process.h settings.h dht.h defines.h qcustomplot.h $(DISTDIR)/
	$(COPY_FILE) --parents lib/QtTelegramBot/qttelegrambot.cpp lib/QtTelegramBot/networking.cpp lib/QtTelegramBot/types/message.cpp lib/QtTelegramBot/types/update.cpp lib/QtTelegramBot/types/chat.cpp lib/QtTelegramBot/types/user.cpp lib/QtTelegramBot/types/document.cpp lib/QtTelegramBot/types/photosize.cpp lib/QtTelegramBot/types/audio.cpp lib/QtTelegramBot/types/sticker.cpp lib/QtTelegramBot/types/video.cpp lib/QtTelegramBot/types/voice.cpp lib/QtTelegramBot/types/contact.cpp lib/QtTelegramBot/types/location.cpp main.cpp widget.cpp process.cpp settings.cpp dht.cpp qcustomplot.cpp $(DISTDIR)/
	$(COPY_FILE) --parents widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/arm-linux-gnueabihf/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qttelegrambot.cpp moc_networking.cpp moc_widget.cpp moc_process.cpp moc_dht.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qttelegrambot.cpp moc_networking.cpp moc_widget.cpp moc_process.cpp moc_dht.cpp moc_qcustomplot.cpp
moc_qttelegrambot.cpp: lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		lib/QtTelegramBot/qttelegrambot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include lib/QtTelegramBot/qttelegrambot.h -o moc_qttelegrambot.cpp

moc_networking.cpp: lib/QtTelegramBot/networking.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include lib/QtTelegramBot/networking.h -o moc_networking.cpp

moc_widget.cpp: process.h \
		settings.h \
		dht.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		widget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include widget.h -o moc_widget.cpp

moc_process.cpp: settings.h \
		dht.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		process.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include process.h -o moc_process.cpp

moc_dht.cpp: dht.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include dht.h -o moc_dht.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /opt/iot/moc_predefs.h -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I/opt/iot -I/opt/iot/lib/mqtt-inc -I/opt/iot/lib/QtTelegramBot -I/usr/include/arm-linux-gnueabihf/qt5 -I/usr/include/arm-linux-gnueabihf/qt5/QtPrintSupport -I/usr/include/arm-linux-gnueabihf/qt5/QtWidgets -I/usr/include/arm-linux-gnueabihf/qt5/QtGui -I/usr/include/arm-linux-gnueabihf/qt5/QtNetwork -I/usr/include/arm-linux-gnueabihf/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/arm-linux-gnueabihf/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/arm-linux-gnueabihf/8/include -I/usr/local/include -I/usr/lib/gcc/arm-linux-gnueabihf/8/include-fixed -I/usr/include/arm-linux-gnueabihf -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui \
		/usr/lib/qt5/bin/uic \
		qcustomplot.h
	/usr/lib/qt5/bin/uic widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

qttelegrambot.o: lib/QtTelegramBot/qttelegrambot.cpp lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qttelegrambot.o lib/QtTelegramBot/qttelegrambot.cpp

networking.o: lib/QtTelegramBot/networking.cpp lib/QtTelegramBot/networking.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networking.o lib/QtTelegramBot/networking.cpp

message.o: lib/QtTelegramBot/types/message.cpp lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o message.o lib/QtTelegramBot/types/message.cpp

update.o: lib/QtTelegramBot/types/update.cpp lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o update.o lib/QtTelegramBot/types/update.cpp

chat.o: lib/QtTelegramBot/types/chat.cpp lib/QtTelegramBot/types/chat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chat.o lib/QtTelegramBot/types/chat.cpp

user.o: lib/QtTelegramBot/types/user.cpp lib/QtTelegramBot/types/user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o lib/QtTelegramBot/types/user.cpp

document.o: lib/QtTelegramBot/types/document.cpp lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o lib/QtTelegramBot/types/document.cpp

photosize.o: lib/QtTelegramBot/types/photosize.cpp lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o photosize.o lib/QtTelegramBot/types/photosize.cpp

audio.o: lib/QtTelegramBot/types/audio.cpp lib/QtTelegramBot/types/audio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audio.o lib/QtTelegramBot/types/audio.cpp

sticker.o: lib/QtTelegramBot/types/sticker.cpp lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sticker.o lib/QtTelegramBot/types/sticker.cpp

video.o: lib/QtTelegramBot/types/video.cpp lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/photosize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video.o lib/QtTelegramBot/types/video.cpp

voice.o: lib/QtTelegramBot/types/voice.cpp lib/QtTelegramBot/types/voice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voice.o lib/QtTelegramBot/types/voice.cpp

contact.o: lib/QtTelegramBot/types/contact.cpp lib/QtTelegramBot/types/contact.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o contact.o lib/QtTelegramBot/types/contact.cpp

location.o: lib/QtTelegramBot/types/location.cpp lib/QtTelegramBot/types/location.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o location.o lib/QtTelegramBot/types/location.cpp

main.o: main.cpp widget.h \
		process.h \
		settings.h \
		dht.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		process.h \
		settings.h \
		dht.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h \
		lib/QtTelegramBot/qttelegrambot.h \
		lib/QtTelegramBot/networking.h \
		lib/QtTelegramBot/types/chat.h \
		lib/QtTelegramBot/types/update.h \
		lib/QtTelegramBot/types/message.h \
		lib/QtTelegramBot/types/audio.h \
		lib/QtTelegramBot/types/document.h \
		lib/QtTelegramBot/types/photosize.h \
		lib/QtTelegramBot/types/sticker.h \
		lib/QtTelegramBot/types/video.h \
		lib/QtTelegramBot/types/voice.h \
		lib/QtTelegramBot/types/contact.h \
		lib/QtTelegramBot/types/location.h \
		lib/QtTelegramBot/types/user.h \
		lib/QtTelegramBot/types/file.h \
		lib/QtTelegramBot/types/reply/genericreply.h \
		lib/QtTelegramBot/types/reply/replykeyboardmarkup.h \
		lib/QtTelegramBot/types/reply/replykeyboardhide.h \
		lib/QtTelegramBot/types/reply/forcereply.h \
		ui_widget.h \
		qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

process.o: process.cpp process.h \
		settings.h \
		dht.h \
		lib/mqtt-inc/qmqtt.h \
		lib/mqtt-inc/qmqtt_message.h \
		lib/mqtt-inc/qmqtt_global.h \
		lib/mqtt-inc/qmqtt_client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o process.o process.cpp

settings.o: settings.cpp settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

dht.o: dht.cpp dht.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dht.o dht.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

moc_qttelegrambot.o: moc_qttelegrambot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qttelegrambot.o moc_qttelegrambot.cpp

moc_networking.o: moc_networking.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networking.o moc_networking.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_process.o: moc_process.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_process.o moc_process.cpp

moc_dht.o: moc_dht.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dht.o moc_dht.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

